### ISSUE TITLE
get_latest_target_branch_commit_sha -> Exit code 128

### ISSUE THREAD

**Issue by pbergen** [ambient-innovation/ambient-toolbox#12]
https://github.com/ambient-innovation/ambient-toolbox/blob/bb8e39e2e9e187da157bd846cb64f034be00cefb/ambient_toolbox/gitlab/coverage.py#L40

`check=True` sollte eventuell wieder entfernt werden, da es zu einem Fehler mit dem Exit Code 128 kommen kann. 

`["git", "merge-base", "--fork-point", f"origin/{self.target_branch}"], stdout=subprocess.PIPE`

Das liegt u.a. daran, dass der shallow clone nicht weit genug in der Historie zurück geht und somit keinen Fork Poink findet.

Alternativ auch die gesamte Funktion entfernen und immer den develop branch  als Vergleich heranziehen.

**Comment by GitRon** [comment]
@pbergen I released a fix and removed the `check=True`. see v.9.2.1
